### ISSUE TITLE
Possible bug: Incorrect function signatures

### ISSUE THREAD

**Issue by joshblum** [macropin/django-registration#150]
The function signatures of the `RegistrationView` class differ throughout the codebase. This seems to be a problem for inheritance:

https://github.com/macropin/django-registration/blob/master/registration/views.py#L63 
has `def register(self, request, form)`.
vs. 
https://github.com/macropin/django-registration/blob/master/registration/backends/default/views.py#L60
https://github.com/macropin/django-registration/blob/master/registration/backends/simple/views.py#L19

which both have `def register(self, form)`.

Is this a bug or is the inconsistency intentional?

**Comment by dicato** [comment]
Thanks for reporting. I'm confident at one point in time that inconsistency was intentional.

My first thought is to standardize on: `register(self, form)`. `request` can always be referenced from `self.request` inside the method. This makes this code consistent with https://github.com/macropin/django-registration/pull/56 as well.

**Comment by joshblum** [comment]
I agree, the PR in #153 conforms to this :)
