### ISSUE TITLE
Include url to resend activation email

### ISSUE THREAD

**Issue by joshblum** [macropin/django-registration#158]
Is there a reason that an endpoint to resend the activation email doesn't exist already? It would be nice to have this so a user can hit an endpoint if they lost the email.

Essentially a wrapper around this function:
https://github.com/macropin/django-registration/blob/master/registration/admin.py#L44

If you guys think it would be good I don't mind implementing :)

**Comment by dicato** [comment]
Would it be an authenticated or anonymous view (or both)?

I verified for my own knowledge that `resend_activation_key` creates a new key only if a corresponding profile with said email exists and has not already been activated or expired; so that's good - https://github.com/macropin/django-registration/blob/f25a0b63da92a49ed07d5be39eafa636a5562295/registration/models.py#L137

**Comment by joshblum** [comment]
I think anon view since authenticated users shouldn't need to register again right?

**Comment by joshblum** [comment]
@lydiagu here is the issue for reference

**Comment by dicato** [comment]
@joshblum oh..yea you are right. I totally confused registered with "verified email" in my mind :see_no_evil:

**Comment by joshblum** [comment]
closed by #161
