### ISSUE TITLE
What is the difference between this and ubernostrum's django-registration?

### ISSUE THREAD

**Issue by edasaki** [macropin/django-registration#177]
Apologies for my naivete, but what is the difference between this django-registration-redux package and the django-registration package maintained by ubernostrum? Both seem to be consistently updated and support similar things. Are these just 2 forks of the original django-registration? Are there any major differences I should take into consideration?

**Comment by dicato** [comment]
No need to apologize :smile:

I can guarantee others know more about the the history of the project, but I can give my own history of why I chose to use this version (and subsequently ended up helping maintain it).

In short, the original django-registration written by ubernostrum was abandoned (for lack of a better word). Since there was still interest in the package it was forked to this repository and work continued. Up until fairy recently, this version was the only actively developed version. Recently, ubernostrum began working on the original version again.

I can't speak to ubernostrum's current version, but this version is active and adopted by many people. However, I will say that if you are looking to adopt a package to help with user registration in Django I would highly recommend considering django-allauth: https://github.com/pennersr/django-allauth

I'm closing this issue but feel free to ask any follow up questions.
