### ISSUE TITLE
setup.py broke for new environments 23 days ago

### ISSUE THREAD

**Issue by yeago** [macropin/django-registration#206]
https://github.com/macropin/django-registration/commit/a1b31a087027502c0c989dfcbf658c617cb28f3c

importing django into setup.py is a piss-poor idea that will break CI environments using this package, to speak nothing of new installs.

**Comment by dicato** [comment]
Good catch. 

Are you interested in trying to fix the issue? For clarity, `setup.py` cannot and should not assume any package dependencies are installed. Compiling locales during installation will need to be rethought. Hopefully @allo- can weigh in as well.

**Comment by yeago** [comment]
sorry, i looked and i don't really see any way to mitigate it given that setup is now subclassing a core lib. maybe some elaborate import scheme but I don't really think that would be compatible with the goal of the commit.

**Comment by allo-** [comment]
What about

    HAS_DJANGO=True
    try:
        import django
    except ImportError:
        HAS_DJANGO=False
    [...]
    if HAS_DJANGO:
        # compile locales
    else:
        print "to compile locales during installation you need to have django installed before installing django-registration. Please run ./manage.py makemessages later"

**Comment by allo-** [comment]
What is the flow of dependencies in setuptools? I guess it should somehow make sure the dependencies are installed before installing the package. Of course it needs to be able to import setup.py to read the dependencies, so there needs to be a conditional import. But maybe some routine later is allowed to import dependencies? That's again the question about the correct routine in setup.py, see https://github.com/macropin/django-registration/pull/189#issuecomment-231827191.

**Comment by yeago** [comment]
maybe. what's the problem with just letting people do this as a management command and adding that to the installation instructions? in most scenarios nobody has any control over the order of things being installed so the message isn't very useful. what precedent (aka other libraries) is there for conducting this work in setup.py at all?

**Comment by allo-** [comment]
Another question is, if a package is supposed to compile the locales? I think the user is supposed to run ``collectstatic`` from his project folder, maybe he should be required to run ``makemessages`` himself, if needed?

To provide binary packages, which work without compiling locales yourself, an new setup.py command "compile_locales" could be defined and called in the build process.

Another thing you need to be aware of is, that django itself has no hard requirement on the system binary for gettext, which is needed to compile locales.

**Comment by felixSchl** [comment]
Would it be OK to simply compile the locales and commit to the repo, [considering that's how the django devs seem to do it](https://github.com/django/django/tree/master/django/contrib/flatpages/locale/af/LC_MESSAGES)?

**Comment by dicato** [comment]
I'm certainly happy with doing it how Django does it.

**Comment by allo-** [comment]
I opened the pull request, because (redundant) binary files in a version control system are kind of a bad smell. The django project may be doing this because they are using transifex, which manages this its own way. I do not know the details, but most projects with transfex do not want pull requests for .po files either, but you should use the web interface.

I think i started the pull request, when i patched some translation and had the problem with differences between the now patched .po and .mo file and ported some code i used myself to this project. I am not sure about CI systems and if they are really working poor with such techniques or if there are solutions.
Personally i do not mind if you revert it, but i would think having "compiled" files in a repo is something you should avoid.

**Comment by felixSchl** [comment]
Couldn't we just generate the files before creating a package using `setup.py bdist` rather than `sdist`? I am not too familiar with packaging for python, but that's a common way to package stuff under npm, for example, where we would compile from some alt js to js as a step before packaging. Seems like Makefile material to me.

**Comment by dicato** [comment]
@allo- I agree that having compiled or binary files in the repo is, in general, bad practice. 

@felixSchl, yes I think we could make it part of the release process.
