### ISSUE TITLE
No  Docs for removing some default URLs

### ISSUE THREAD

**Issue by theparadoxer02** [macropin/django-registration#238]
I want to remove some of the URL predefined in this registration library and use all its other feature , so how one can do that . 
Lets suppose I want to delete the 'account/register' link and will do it manually . Then There is no option and and docs defined to remove that particular or custom URL .
There should be some custom **URL remove option**.

**Comment by macropin** [comment]
There are a few ways to do this: You could write your own backend, complete with custom `urls.py` or you could use one of the supplied backends with your own url definition.

**Comment by theparadoxer02** [comment]
if i am following the second way , then how do i fullly remove the url  so that no one can access it ?

**Comment by joshblum** [comment]
@theparadoxer02 instead of including the (default urls)[http://django-registration-redux.readthedocs.io/en/latest/quickstart.html#setting-up-urls]

`(r'^accounts/', include('registration.backends.default.urls')),`
 you can only add the ones you one available by picking and choosing from the included file.
