### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by nehri97** [macropin/django-registration#99]
I have the impression that the documentation was intended for those migrating from django-registration to redux. Many complain that the documentation could be much better. It would be nice if aside from the very introductory topics (like installation), there would be intermediate steps for those who came straight to django-registration-redux but would want more info on customizing it for their own needs.

**Comment by macropin** [comment]
I'm happy to accept a PR with improvements.

**Comment by ahammouda3** [comment]
One point on the documentation front would be to note that in order to override the admin templates for password reset functionality, you need to do the following:

     $ mkdir $TEMPLATE_DIR/registration
     $ mv django_registration/registration/templates/registration/password_* $TEMPLATE_DIR/registration

I don't know that this is obvious, or the best way to do things.  If no one has made a PR with this addition, I'll do so when I get a chance (someday...).

**Comment by dicato** [comment]
@ahammouda3 it's not obvious, and tends to be the "way to do it" for any Django application. If you can, please make the changes and open a pull request. :smile:

**Comment by dicato** [comment]
@nehri97 and @ahammouda3 are either of you able to improve the documentation in a pull request? :smile:
